name: Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 13 ]
    name: Test on java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache SBT ivy cache
        uses: OlegYch/cache@posixv1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-ivy-

      - name: Cache SBT
        uses: OlegYch/cache@posixv1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-java-${{ matrix.java }}-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-sbt-java-${{ matrix.java }}-

      - name: Cache coursier cache
        uses: OlegYch/cache@posixv1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-coursier-

      - name: Cache project
        uses: OlegYch/cache@posixv1
        with:
          path: ./
          key: ${{ runner.os }}-project-java-${{ matrix.java }}-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-project-java-${{ matrix.java }}-

      - name: Checkout current
        run: git checkout . && git clean -df
      - name: Run tests
        run: export DB_PASSWORD=DB_PASSWORD && export SBT_OPTS=-Xmx4g && sbt 'eval java.lang.management.ManagementFactory.getRuntimeMXBean().getInputArguments();+cachedCiTest'
      - name: Clean caches
        run: |
          rm -fv ~/.ivy2/.sbt.ivy.lock
          find ~/.ivy2/cache -name "ivydata-*.properties" -print -delete || echo "empty ivy cache"
          find ~/.sbt        -name "*.lock"               -print -delete
          rm -rf ./.git
          rm -rf ./project/target #clean doesn't clean meta-build
